//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighChartsColumn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOEAdminDbEntities1 : DbContext
    {
        public MOEAdminDbEntities1()
            : base("name=MOEAdminDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SCHOOLS_DATA> SCHOOLS_DATA { get; set; }
        public virtual DbSet<SCHOOLS_DATA_FANY> SCHOOLS_DATA_FANY { get; set; }
        public virtual DbSet<TEACHERS_DATA> TEACHERS_DATA { get; set; }
        public virtual DbSet<TEACHERS_DATA_FANY> TEACHERS_DATA_FANY { get; set; }
        public virtual DbSet<STUDENTS_DATA> STUDENTS_DATA { get; set; }
        public virtual DbSet<STUDENTS_DATA_FANY> STUDENTS_DATA_FANY { get; set; }
    }
}
