//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighChartsColumn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHOOLS_DATA_FANY
    {
        public decimal School_ID { get; set; }
        public string School_Name { get; set; }
        public Nullable<decimal> District_ID { get; set; }
        public string City { get; set; }
        public string EMAIL { get; set; }
        public decimal Id { get; set; }
    }
}
