//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighChartsColumn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHERS_DATA_FANY
    {
        public decimal Teacher_ID { get; set; }
        public decimal SCHOOL_ID { get; set; }
        public string Emailaddress { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public decimal Id { get; set; }
    }
}
